apiVersion: v1
kind: Service
metadata:
  labels:
    app: strigus
  name: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: strigus
  sessionAffinity: None
  type: ClusterIP
