apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: strigus
  name: strigus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strigus
  template:
    metadata:
      labels:
        app: strigus
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: 64Mi
            requests:
              cpu: "0.25"
              memory: 32Mi
